using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MongoDB.Bson.Serialization.Attributes;

namespace UTDDesignMongoDemo.Models
{
    [BsonIgnoreExtraElements] //This is need so mongo doesn't throw erros saying it doesn't have a place to store the autogenerated id for the object.(We don't need to id so this says to ignore it)
    public class AppointmentDemoModel
    {
        [BsonElement("last_name")]
        public string LastName { get; set; }

        [BsonElement("first_name")]
        public string FirstName { get; set; }

        [BsonElement("calender_name")]
        public string CalendarName { get; set; }

        [BsonElement("start_datetime")]
        public DateTime StartDateTime { get; set; }

        [BsonElement("end_datetime")]
        public DateTime EndDateTime { get; set; }

        [BsonElement("reason")]
        public string Reason { get; set; }
    }
}
